name: Refresh data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: EvergreenAdmx
        # Install-Script -Name EvergreenAdmx
        run: |
          .\.github\EvergreenAdmx.ps1 -Verbose -WorkingDirectory . -Include @(
            "Windows 11"
            "Microsoft Edge"
            "Microsoft OneDrive"
            "Microsoft Office"
            "FSLogix"
            "Adobe Acrobat"
            "Adobe Reader"
            "BIS-F"
            "Citrix Workspace App"
            "Google Chrome"
            "Microsoft Desktop Optimization Pack"
            "Mozilla Firefox"
            "Zoom Desktop Client"
            "Azure Virtual Desktop"
            "Microsoft Winget"
          )
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: Change detected
