name: Refresh data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4.3.0
      - uses: actions/setup-node@v4.2.0
        with:
          cache: 'pnpm'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y p7zip-full
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
      - name: Fetch ADMX and ADML files
        run: npx tsx scripts/fetch-admx.ts
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: Updated ADMX generated data

  lint:
    needs: main
    runs-on: ubuntu-latest
    container:
      image: fstossesds/admx-lint
      options: --user root
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: Lint ADMX
        run: |
          for file in admx/*.admx; do
            admx-lint --input_file "$file" || true
          done
