name: Refresh data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: EvergreenAdmx
        # note conflicts - MDOP is partially superseded by Windows, and Windows ships an old winget version in-box
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/pl4nty/EvergreenAdmx/refs/heads/main/EvergreenAdmx.ps1 -OutFile $env:TEMP\EvergreenAdmx.ps1
          & $env:TEMP\EvergreenAdmx.ps1 -Verbose -WorkingDirectory . -Include @(
            "Windows 11"
            "Microsoft Edge"
            "Microsoft OneDrive"
            "Microsoft Office"
            "FSLogix"
            "Adobe Acrobat"
            "Adobe Reader"
            "BIS-F"
            "Citrix Workspace App"
            "Google Chrome"
            "Microsoft Desktop Optimization Pack"
            "Mozilla Firefox"
            "Zoom Desktop Client"
            "Azure Virtual Desktop"
            "Microsoft Winget"
            "Brave Browser"
          )

      - uses: actions/setup-node@v4.2.0
        with:
          cache: 'npm'
      - name: admx2json
        working-directory: admx
        run: |
          npm i fast-xml-parser
          node ../src/utils/admx2json.js .

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: Updated ADMX data

      - uses: actions/upload-artifact@v4.6.0
        with:
          path: admx
  lint:
    needs: main
    runs-on: ubuntu-latest
    container:
      image: fstossesds/admx-lint
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: artifact
          path: /home/appuser
      - name: lint ADMX
        working-directory: /home/appuser/admx
        run: |
          for file in *.admx; do
            admx-lint --input_file "$file"
          done
